apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: pidevagentai
type: Opaque
stringData:
  JWT_SECRET: replace-me
  MONGO_URI: mongodb+srv://username:password@cluster.mongodb.net/pidevagentai
  OPENAI_API_KEY: replace-me
  GOOGLE_CLIENT_SECRET: replace-me
